version: "3.7"
services:
  caddy:
    image: caddy:2.4.6-alpine
    restart: unless-stopped
    command: caddy reverse-proxy --from https://fical.nikolak.com:443 --to http://fical:8080
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
    depends_on:
      - fical

  fical:
    image: ghcr.io/nikolak/fical:main
    environment:
      - PORT=8080

volumes:
  caddy: { }